### ISSUE TITLE
Update the Readme of this repository

### ISSUE THREAD

**Issue by dokasto** [UceeCode/tank-titans#1]
- Add description
- Add link to the game
- Add a screenshot of the game 
- Talk about the technologies used.

**Comment by dokasto** [comment]
I see you update it but the link to play the game is broke

<img width="510" alt="Screenshot 2024-06-07 at 4 58 57 PM" src="https://github.com/UceeCode/tank-titans/assets/3197630/6b01529e-b871-4d79-bcf5-4ab7ba5fb7c7">

**Comment by UceeCode** [comment]
fixed it 👍
