### ISSUE TITLE
Add stages

### ISSUE THREAD

**Issue by iemeka** [UceeCode/tank-titans#9]
speed of enemies increase with stages

**Comment by UceeCode** [comment]
i made the speed increase as the score increases. Is that okay ?

**Comment by iemeka** [comment]
That's fine. 
- Let's have a range of score
- speed remains constant for each range.
- Each range is a stage.
- Add stage to the ui design and
- When you get to the end of a stage / get to a certain score:
   - Increase speed
   - Increase stage in UI

**Comment by UceeCode** [comment]
Done
